include: package:very_good_analysis/analysis_options.7.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/packages/**"
    - "**/development_firebase_options.dart"
    - "**/production_firebase_options.dart"
