name: Build & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.29.2'
      - name: Install os dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: sora-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: build/linux/x64/release/bundle/sora-${{github.ref_name}}-linux.zip
  
  # build-and-release-windows:
  #   runs-on: windows-latest

  # build-and-release-macos:
  #   runs-on: macos-latest