name: Build & Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
   build-and-release-linux-zip_AppImage_RPM:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install webkit2gtk-4.1 clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev libblkid-dev liblzma-dev fuse rpm
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/
      
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install the CLI tool
        run: cargo install 'flutter_rust_bridge_codegen'

      - name: flutter pub get
        run: flutter pub get

      - name: build linux
        run: flutter build linux --release

      - name: Zip
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Sora-${{ github.ref_name }}-linux.zip
          directory: build/linux/x64/release/bundle
      
      - name: Create AppImage
        run: |
          # Create fresh AppDir structure
          rm -rf AppDir
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          # Copy built files
          cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/
          cp assets/images/sora_logo.png AppDir/usr/share/icons/hicolor/256x256/apps/sora.png
          cp assets/images/sora_logo.png AppDir/sora.png
          # Create desktop file in AppDir root
          cat <<EOF > AppDir/sora.desktop
          [Desktop Entry]
          Name=sora
          Exec=usr/bin/sora
          Icon=sora
          Type=Application
          Categories=Utility;
          EOF
          # Create AppRun file
          cat <<EOF > AppDir/AppRun
          #!/bin/sh
          SELF=\$(readlink -f "\$0")
          HERE=\${SELF%/*}
          export PATH="\${HERE}/usr/bin/:\${PATH}"
          export LD_LIBRARY_PATH="\${HERE}/usr/lib/:\${LD_LIBRARY_PATH}"
          exec "\${HERE}/usr/bin/sora" "\$@"
          EOF
          chmod +x AppDir/AppRun
          # Make AppImage
          /usr/local/bin/appimagetool AppDir
          mv $(find . -type f -name "*.AppImage") build/linux/x64/release/Sora-${{ github.ref_name }}-linux.AppImage
      
      - name: Create RPM Package
        run: |
          mkdir -p rpm_build/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp -r build/linux/x64/release/bundle rpm_build/SOURCES/sora-1.0.0
          tar czf rpm_build/SOURCES/sora-1.0.0.tar.gz -C rpm_build/SOURCES sora-1.0.0
          mkdir -p rpm_build/SOURCES/usr/share/icons/hicolor/256x256/apps
          cp assets/images/sora_logo.png rpm_build/SOURCES/usr/share/icons/hicolor/256x256/apps/sora.png
          # RPM Spec File
          cat <<EOF > rpm_build/SPECS/sora.spec
          Name: sora
          Version: 1.0.0
          Release: 1%{?dist}
          Summary: Sora is an open-source GUI for gallery-dl
          License: MIT
          Source0: %{name}-%{version}.tar.gz
          BuildArch: x86_64
          %description
          Sora is an open-source GUI for gallery-dl.
          %prep
          %setup -q
          %install
          mkdir -p %{buildroot}/usr/bin
          mkdir -p %{buildroot}/usr/share/applications
          mkdir -p %{buildroot}/usr/share/icons/hicolor/256x256/apps
          cp -r * %{buildroot}/usr/bin/
          cp -r %{_sourcedir}/usr/share/* %{buildroot}/usr/share/
          cat <<EOL > %{buildroot}/usr/share/applications/sora.desktop
          [Desktop Entry]
          Name=sora
          Exec=/usr/bin/sora
          Icon=sora
          Type=Application
          Categories=Utility;
          EOL
          %files
          /usr/bin/*
          /usr/share/applications/sora.desktop
          /usr/share/icons/hicolor/256x256/apps/sora.png
          EOF
          rpmbuild --define "_topdir $(pwd)/rpm_build" -ba rpm_build/SPECS/sora.spec
          mv rpm_build/RPMS/x86_64/*.rpm build/linux/x64/release/Sora-${{ github.ref_name }}-linux.rpm
      
      - name: upload artifact linux zip
        uses: actions/upload-artifact@v4
        with:
          name: Sora-${{ github.ref_name }}-linux-zip
          path: |
            build/linux/x64/release/bundle/Sora-*.zip
            build/linux/x64/release/Sora-*.AppImage
            build/linux/x64/release/Sora-*.rpm
      - name: release packages linux zip
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/linux/x64/release/bundle/Sora-*.zip
            build/linux/x64/release/Sora-*.AppImage
            build/linux/x64/release/Sora-*.rpm
          allowUpdates: true